# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ci

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup dotnet 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --nologo

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack FluentResults
      run: dotnet pack .\src\FluentResults\FluentResults.csproj --no-build --output artifacts

    - name: Pack FluentResults.Extensions.AspNetCore
      run: dotnet pack .\src\FluentResults\FluentResults.Extensions.AspNetCore.csproj --no-build --output artifacts

    - name: Pack FluentResults.Extensions.FluentAssertions
      run: dotnet pack .\src\FluentResults\FluentResults.Extensions.FluentAssertions.csproj --no-build --output artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts/**/*
