# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release

on: workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --nologo

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack FluentResults
      run: dotnet pack .\src\FluentResults\FluentResults.csproj --no-build --output nupkgs

    - name: Pack FluentResults.Extensions.AspNetCore
      run: dotnet pack .\src\FluentResults\FluentResults.Extensions.AspNetCore.csproj --no-build --output nupkgs

    - name: Pack FluentResults.Extensions.FluentAssertions
      run: dotnet pack .\src\FluentResults\FluentResults.Extensions.FluentAssertions.csproj --no-build --output nupkgs

    - name: Upload nupkgs
      uses: actions/upload-artifact@v3
      with:
        name: nupkgs
        path: '**/nupkgs/*'
